# Site settings
title: OAuth for ASP.NET
email: jerrie@jerriepelser.com
description: > # this means to ignore newlines until "baseurl:"
  Providers quick reference guides on how to use the various OAuth provides with ASP.NET 5
baseurl: "/oauthforaspnet/" # the subpath of your site, e.g. /blog/
url: "http://matthewdunsdon.github.io/oauthforaspnet/" # the base hostname & protocol for your site
twitter_username: beabigrockstar
github_username:  jerriep

# Build settings
markdown: kramdown
highlighter: pygments

permalink: /:categories/:title

exclude:      ["bower_components", "node_modules", "gulpfile.js", "bower.json", "package.json"]

kramdown:
  input: GFM

gems:
  - jekyll-sitemap
